language: generic
sudo: true
dist: xenial
go:
  - "1.12"
env:
- GO111MODULE=on

before_script:
  - wget -qO- https://releases.hashicorp.com/consul/1.6.2/consul_1.6.2_linux_amd64.zip | zcat >> /tmp/consul
  - chmod +x /tmp/consul && /tmp/consul agent -dev &

script:
  - make test
